# Generated by Django 3.2.3 on 2021-05-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Swords', '0002_remove_words_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ur', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='words',
            name='url',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Swords.url'),
            preserve_default=False,
        ),
    ]
